### ISSUE TITLE
handle errors while calling the api

### ISSUE THREAD

**Issue by hofstede-matheus** [nota-de-corretagem-to-csv/nota-de-corretagem-to-csv-react#3]
The app does nothing when the request fails.
Adding a try/catch in the service and returning an error (and giving the user feedback) is excellent.

**Comment by SubinDuresh** [comment]
Hi @hofstede-matheus can I work on this issue? I can add a small error message display below the main content.

**Comment by hofstede-matheus** [comment]
Hi @SubinDuresh thanks for your help.
This is a project that makes sense for Brazilian people, so I think that message should be in Brazilian Portuguese.
Can you please make the error message:
**"Algo deu errado. Tente novamente em alguns minutos"**
Also, the input value should be reseted too, as it is when the request runs fine.
